version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfiles/backend.dockerfile
    ports:
      - "8080:8080"
    environment:
      - API_KEY_FILE=/app/api_key.txt
    volumes:
      - ./api_key.txt:/app/api_key.txt
      - ./currency_codes.txt:/app/currency_codes.txt
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfiles/frontend.dockerfile
    ports:
      - "3000:80"
