version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: currencydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/java/com/vladcranga/currencyconverter/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfiles/backend.dockerfile
    ports:
      - "8080:8080"
    environment:
      - API_KEY_FILE=/app/api_key.txt
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/currencydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - ./api_key.txt:/app/api_key.txt
      - ./currency_codes.txt:/app/currency_codes.txt
    depends_on:
      - frontend
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfiles/frontend.dockerfile
    ports:
      - "3000:80"
